import { useEffect, useState } from "react";
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { ArrowDown, ArrowLeft, ArrowRight, Check, ChevronDown, Search, Sparkles } from "lucide-react";
import { careersDb } from "@/careersDb";
import { careerContent } from "@/careerContent";
import { CareerSalary } from "@/components/CareerSalary";
import { BeforeYouChoose } from "@/components/BeforeYouChoose";
import { RealityCheckCTA } from "@/features/reality-check/components/RealityCheckCTA";
import AssessmentPage from "@/features/reality-check/AssessmentPage";
import ResultsPage from "@/features/reality-check/ResultsPage";
import "@/App.css";

const illustrations = {
  nurse: "https://static.prod-images.emergentagent.com/jobs/3fe5856b-df10-4c39-a0e6-7f90c6f28360/images/0e1230e354eff705b659385c545d830e41d7c9a75f9b86a5c1211bf0058942f8.jpeg",
  "software-developer": "https://static.prod-images.emergentagent.com/jobs/3fe5856b-df10-4c39-a0e6-7f90c6f28360/images/3f1b8e269fbe320e8cae4bbe0058f73830d3385890d3f71276f5e40cc68ff0de.jpeg",
  doctor: "https://static.prod-images.emergentagent.com/jobs/3fe5856b-df10-4c39-a0e6-7f90c6f28360/images/a8cd4f7abf5f3bfc4b1581d5c8e15313fadfac1463416bfa1beb3896606b933c.jpeg",
  "chartered-accountant": "https://static.prod-images.emergentagent.com/jobs/3fe5856b-df10-4c39-a0e6-7f90c6f28360/images/5d27352bfe2ea55159f1133096c9b13814bd17926cb0a416f49db75310901439.jpeg",
  entrepreneur: "https://static.prod-images.emergentagent.com/jobs/3fe5856b-df10-4c39-a0e6-7f90c6f28360/images/c9d5b7723ac7c7388e07d9a00ceea91357dcabb571a8d5a9fa31876ec1226483.jpeg",
};
const artFor = slug => illustrations[slug] || illustrations.entrepreneur;

const careers = careersDb.map(c => careerContent[c.slug]);

function Brand({ light = false }) { return <Link to="/" className={`brand ${light ? "brand-light" : ""}`} data-testid="brand-home-link"><span className="brand-mark"><Sparkles size={15} strokeWidth={3} /></span>CAREERPEEK</Link>; }
function BackLink({ children = "Back" }) { const { pathname } = useLocation(); const { slug } = useParams(); const career = careers.find(item => item.slug === slug); const to = career && pathname === `/careers/${slug}/roadmap` ? `/careers/${slug}` : pathname === "/careers" ? "/" : "/careers"; return <Link className="back-link" to={to} data-testid="back-button"><ArrowLeft size={16} /> {children}</Link>; }
function PageShell({ children, className = "" }) { return <div className={`page-shell ${className}`}><header className="topbar"><Brand /><Link to="/careers" className="explore-nav" data-testid="header-careers-link">Explore careers <ArrowRight size={15} /></Link></header>{children}</div>; }

function Home() { const navigate = useNavigate(); return <main className="home-page"><div className="home-grid-pattern" /><header className="topbar home-topbar"><Brand /></header><section className="home-hero"><div className="home-copy reveal"><h1>CAREER<em>PEEK</em></h1><p className="home-lead">Your future doesn’t have to be a guess.</p><p className="home-sub">Explore careers, see what the work is really like, and discover what might fit you.</p><button className="primary-button hero-button" onClick={() => navigate("/careers")} data-testid="home-start-button">Let’s Start <ArrowRight size={19} /></button></div><div className="home-art reveal-delay"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-scribble">✦</div><div className="hero-badge">CURIOUS<br /><strong>LOOKS GOOD<br />ON YOU</strong></div><img src={illustrations.entrepreneur} alt="Friendly student exploring career ideas" data-testid="home-hero-illustration" /></div></section><div className="home-footer"><span>01 / BEGIN HERE</span><span>Scroll less. Discover more.</span></div></main>; }

function Careers() { const [query, setQuery] = useState(""); const q = query.trim().toLowerCase(); const matches = q ? careers.filter(c => `${c.name} ${c.description} ${c.cardDescription}`.toLowerCase().includes(q)) : careers; const totalCount = matches.length; const metaLabel = q ? `${totalCount} match${totalCount === 1 ? "" : "es"}` : `${totalCount} paths to explore`; return <PageShell><main className="directory page-content"><BackLink /><div className="directory-intro"><div className="eyebrow"><span className="eyebrow-dot" /> PICK A DIRECTION</div><h1>WHAT ARE YOU<br /><em>CURIOUS ABOUT?</em></h1><p>Search for a career or explore the options below.</p></div><div className="search-wrap"><Search size={20} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search careers…" aria-label="Search careers" data-testid="career-search-input" /></div><div className="directory-meta"><span data-testid="career-result-count">{metaLabel}</span><span className="meta-line" /></div>{matches.length > 0 && <div className="career-grid">{matches.map((career, index) => <CareerCard career={career} index={index} key={career.slug} />)}</div>}{totalCount === 0 && <div className="empty-state" data-testid="career-empty-state">No paths found yet. Try a different word?</div>}</main></PageShell>; }
function CareerCard({ career, index }) { return <article className={`career-card ${career.color}`} style={{ "--delay": `${index * 80}ms` }} data-testid={`career-card-${career.slug}`}><div className="card-top"><span className="card-number">0{index + 1}</span><span className="card-tag">{career.tag}</span></div><div className="card-visual"><img src={illustrations[career.slug]} alt={`${career.name} illustration`} data-testid={`career-card-image-${career.slug}`} /><div className="card-sun" /></div><div className="card-content"><h2>{career.name}</h2><p>{career.cardDescription}</p><Link to={`/careers/${career.slug}`} className="text-button" data-testid={`career-explore-${career.slug}`}>Explore <ArrowRight size={16} /></Link></div></article>; }

function Detail({ career }) { return <PageShell><main className="detail page-content"><BackLink>Back to careers</BackLink><section className={`detail-hero ${career.color}`}><div className="detail-hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> A CLOSER LOOK</div><h1>{career.name}</h1><p className="detail-tagline">{career.description}</p><p className="detail-intro">{career.intro}</p></div><div className="detail-art"><img src={artFor(career.slug)} alt={`${career.name} character`} data-testid="career-detail-illustration" /><span className="art-sticker">A DAY<br /><strong>IN THE LIFE</strong></span></div></section><section className="detail-section"><SectionHeading eyebrow="01 / THE REAL WORK" title="WHAT YOU’D ACTUALLY DO" copy="A peek at the things that fill your time and why they matter." /><div className="task-grid">{career.tasks.map((task, index) => <div className="task-item" key={task} data-testid={`career-task-${index}`}><span className="task-dot" aria-hidden="true" /><span>{task}</span></div>)}</div></section><section className="detail-section day-section"><SectionHeading eyebrow="02 / A SNAPSHOT" title="A TYPICAL DAY" copy={career.dayCopy || "Every day is different, but here’s one version of how the rhythm might flow."} /><div className="day-body"><div className="timeline" data-testid="career-timeline">{career.timeline.map(([time, event], index) => <div className="timeline-item" key={time}><div className="timeline-time">{time}</div><div className="timeline-line"><span className="timeline-dot" />{index < career.timeline.length - 1 && <span className="timeline-connector" />}</div><div className="timeline-event">{event}</div></div>)}</div><div className="day-illustration" aria-hidden="true"><img src={artFor(career.slug)} alt="" data-testid="day-illustration" /></div></div></section><section className="detail-section skills-section"><SectionHeading eyebrow="03 / YOUR TOOLKIT" title="SKILLS THAT MATTER" copy="You don’t need every skill on day one. These are the ones you’ll keep growing." /><div className="skill-list">{career.skills.map(skill => <span className="skill-chip" key={skill} data-testid={`skill-chip-${skill.toLowerCase().replaceAll(" ", "-")}`}>{skill}</span>)}</div></section><BeforeYouChoose content={career.beforeYouChoose} heading="SOMETHING WORTH KNOWING FIRST." perspective={career.firstHandPerspective} /><section className="roadmap-cta" data-testid="roadmap-cta"><div><span className="eyebrow eyebrow-light"><span className="eyebrow-dot" /> NEXT STOP</span><h2>WANT TO KNOW HOW<br />TO GET THERE?</h2><p>See the full journey from where you are now to becoming a {career.name.toLowerCase()}.</p></div><Link to={`/careers/${career.slug}/roadmap`} className="light-button" data-testid="show-roadmap-button">See full roadmap <ArrowRight size={18} /></Link></section></main></PageShell>; }
function SectionHeading({ eyebrow, title, copy }) { return <div className="section-heading"><div><span className="eyebrow"><span className="eyebrow-dot" /> {eyebrow}</span><h2>{title}</h2></div><p>{copy}</p></div>; }

function Roadmap({ career }) { const [open, setOpen] = useState(null); const steps = career.roadmap; return <PageShell><main className="roadmap page-content"><BackLink>Back to {career.name}</BackLink><section className="roadmap-intro"><div><div className="eyebrow"><span className="eyebrow-dot" /> YOUR NEXT CHAPTER</div><h1>YOUR ROADMAP TO<br /><em>BECOMING A {career.name.toUpperCase()}</em></h1><p>Here’s what the journey can look like. Take it one step at a time.</p></div><div className="roadmap-figure"><img src={artFor(career.slug)} alt={`${career.name} character`} data-testid="roadmap-illustration" /><span>YOU’VE<br /><strong>GOT THIS</strong></span></div></section><section className="journey" data-testid="roadmap-journey"><div className="journey-line" />{steps.map(([title, description, extra], index) => <div className={`milestone-row ${index % 2 ? "reverse" : ""}`} key={title}><button className={`milestone-node ${open === index ? "selected" : ""}`} onClick={() => setOpen(open === index ? null : index)} data-testid={`roadmap-milestone-${index}`} aria-expanded={open === index}><span>{String(index + 1).padStart(2, "0")}</span><ChevronDown size={18} /></button><div className="milestone-card"><span className="milestone-label">STEP {String(index + 1).padStart(2, "0")}</span><h2>{title}</h2><p>{description}</p><button className="milestone-more" onClick={() => setOpen(open === index ? null : index)} data-testid={`roadmap-expand-${index}`}>{open === index ? "Close details" : "See more"} <ArrowDown size={14} /></button>{open === index && <div className="milestone-extra" data-testid={`roadmap-details-${index}`}><Check size={15} /> {extra}</div>}</div></div>)}</section><CareerSalary career={career} /><RealityCheckCTA career={career} /><div className="roadmap-return-actions"><Link to={`/careers/${career.slug}`} className="text-button" data-testid="roadmap-back-to-career"><ArrowLeft size={16} /> Back to career details</Link><Link to="/careers" className="text-button" data-testid="explore-another-career-link">Explore another career <ArrowRight size={16} /></Link></div></main></PageShell>; }

function AppRoutes() { return <Routes><Route path="/" element={<Home />} /><Route path="/careers" element={<Careers />} /><Route path="/careers/:slug/roadmap" element={<RoadmapRoute />} /><Route path="/careers/:slug/reality-check" element={<RealityCheckRoute />} /><Route path="/careers/:slug/reality-check/results" element={<RealityCheckRoute results />} /><Route path="/careers/:slug" element={<CareerRoute />} /><Route path="*" element={<Home />} /></Routes>; }
function ScrollToTop() { const { pathname } = useLocation(); useEffect(() => { if ("scrollRestoration" in window.history) { window.history.scrollRestoration = "manual"; } window.scrollTo(0, 0); }, [pathname]); return null; }
function resolveCareer(slug) { return careers.find(c => c.slug === slug) || null; }
function CareerRoute() { const { slug } = useParams(); const career = resolveCareer(slug); return career ? <Detail career={career} /> : <Careers />; }
function RoadmapRoute() { const { slug } = useParams(); const career = resolveCareer(slug); return career ? <Roadmap career={career} /> : <Careers />; }
function RealityCheckRoute({ results = false }) { const { slug } = useParams(); const career = resolveCareer(slug); if (!career) return <Careers />; return <PageShell>{results ? <ResultsPage key={`${slug}-results`} career={career} illustration={artFor(slug)} artFor={artFor} /> : <AssessmentPage key={slug} career={career} illustration={artFor(slug)} />}</PageShell>; }
export default function App() { return <BrowserRouter><ScrollToTop /><AppRoutes /></BrowserRouter>; }