// Hand-written content for the original five careers, preserved during the
// library-only cleanup. Active routes are restricted by careersDb.js.

export const careerContent = {

  "nurse": {
    slug: "nurse",
    name: "Nurse",
    color: "mint",
    tag: "Healthcare",
    description: "Care for people when they need it most.",
    cardDescription: "Nurses are the heartbeat of healthcare, looking after patients, supporting families, and helping people heal.",
    intro: "Nursing is a hands-on career built around clinical care, calm decision-making and making someone's difficult day a little easier.",
    tasks: [
      "Assess patients on admission and monitor their vital signs through the shift",
      "Give medications, injections and IV fluids exactly as prescribed",
      "Support doctors during examinations, procedures and emergencies",
      "Maintain infection control and hygiene standards on the ward",
      "Keep clear patient records and hand over accurately to the next shift",
      "Comfort patients and answer questions from their families",
      "Educate patients on wound care, medication and lifestyle at discharge",
    ],
    dayCopy: "Nursing schedules vary by hospital and specialty. This is one example of a general-ward day shift; night shifts, ICU and OT rhythms look different.",
    timeline: [
      ["7:00", "Take handover from the night team"],
      ["8:00", "Morning ward rounds and record vitals"],
      ["9:30", "Give scheduled medications and support morning procedures"],
      ["11:00", "Round with doctors on assigned patients"],
      ["13:00", "Lunch and afternoon medications"],
      ["15:00", "Support families and prepare discharge instructions"],
      ["17:00", "Update patient records"],
      ["18:30", "Hand over to the next shift"],
    ],
    skills: [
      "Patient assessment",
      "Vital signs monitoring",
      "Medication administration",
      "Clinical procedures",
      "Infection control",
      "Clinical documentation",
      "Empathy",
      "Clear communication",
      "Staying calm under pressure",
      "Emotional resilience",
      "Teamwork",
    ],
    roadmap: [
      ["STARTING POINT", "In Class 11-12, focus on biology, chemistry and English. Volunteering with a community or healthcare initiative can help you see whether patient-facing work suits you.", "Look for chances to observe a hospital, learn first aid or spend time around care teams."],
      ["EDUCATION / COURSE OPTIONS", "Common routes in India include B.Sc. Nursing (4 years), Post Basic B.Sc. Nursing for GNM holders, and the GNM diploma (a 3-year nursing diploma). Entry is via state or institutional entrance exams and NEET-UG for many B.Sc. Nursing programmes.", "Compare Indian Nursing Council (INC) recognised institutions, practical training hours and clinical postings before deciding."],
      ["CLINICAL EXPERIENCE", "Complete supervised hospital and community clinical postings during your course, covering wards, OT, ICU, maternity and community health.", "Use each posting to understand what type of nursing environment you might enjoy."],
      ["QUALIFICATION / REGISTRATION", "After completing your course, register as a nurse with your State Nursing Council under the Indian Nursing Council framework to practise legally.", "Keep a checklist of documents, fees and renewal timelines for your state."],
      ["FIRST JOB / ENTRY POINT", "Target staff nurse, junior nurse, community health nurse or hospital trainee roles at hospitals, clinics, government health services or NGOs.", "Your first role is where classroom learning turns into confident everyday practice."],
      ["SPECIALIZATION / GROWTH", "Grow through experience, in-service training or a post-basic diploma / M.Sc. Nursing into areas like paediatrics, ICU, emergency, cardiac, oncology, mental health, public health, nurse educator or nursing leadership.", "Nursing skills also travel abroad after fulfilling the destination country's registration requirements."],
    ],
    salary: [["STARTING OUT", "₹2.4L – ₹4.5L"], ["MID-CAREER", "₹4.5L – ₹8L"], ["EXPERIENCED", "₹8L+"]],
    salaryNote: "Government and large private hospitals often follow pay-scale structures. Salaries in metros and specialist units (ICU, OT, cardiac) tend to be higher; nurses abroad usually earn significantly more after fulfilling that country's registration.",
    firstHandPerspective: "Nursing involves much more than clinical procedures. Communication with patients and families, careful documentation, working across shifts and adapting to changing patient needs are just as much a part of the job as the medical side.",
  },

  "software-developer": {
    slug: "software-developer",
    name: "Software Developer",
    color: "sky",
    tag: "Technology",
    description: "Turn ideas into tools people use every day.",
    cardDescription: "Software developers solve problems with code, turning thoughtful ideas into apps, websites and tools people rely on.",
    intro: "Development is part logic, part creativity and a lot of curiosity. Most of the job is turning a real problem into working, maintainable software.",
    tasks: [
      "Write and maintain application code in one or more programming languages",
      "Turn product requirements and designs into working features",
      "Read and understand existing code before making changes to it",
      "Debug and fix software issues reported by users or teammates",
      "Review pull requests and give feedback on other people's code",
      "Work with APIs, databases, Git and testing frameworks",
      "Test features locally and monitor them after they are released",
      "Break large problems into smaller, ship-able changes",
    ],
    timeline: [
      ["9:00", "Check messages, tickets and priorities"],
      ["10:00", "Work on a feature or fix a software issue"],
      ["11:30", "Team stand-up"],
      ["12:00", "Continue development and write tests"],
      ["13:30", "Lunch"],
      ["14:30", "Code review or debugging"],
      ["16:00", "Pair with a teammate on a tricky issue"],
      ["17:30", "Update tickets, commit changes and plan tomorrow"],
    ],
    skills: [
      "Programming",
      "Data structures & algorithms",
      "Databases (SQL, NoSQL)",
      "Version control (Git)",
      "APIs",
      "Debugging",
      "Software testing",
      "Problem solving",
      "Attention to detail",
      "Continuous learning",
      "Communication",
      "Collaboration",
    ],
    roadmap: [
      ["STARTING POINT", "In Class 11-12, focus on maths and logical thinking. Try building small websites, automations or games to see what excites you before picking a college route.", "A simple project you can explain end-to-end is worth more than a long list of tutorials you have watched."],
      ["EDUCATION / COURSE OPTIONS", "Common routes in India include B.Tech / B.E. in Computer Science, Information Technology or related branches, BCA, B.Sc. Computer Science and MCA. Portfolio-based and self-taught routes with strong project work also succeed, especially in product companies and startups.", "Choose a route that gives you programming, data structures and hands-on practice, not only theory."],
      ["PRACTICAL EXPERIENCE", "Build a portfolio of projects on GitHub, contribute to open source, join college hackathons and take up internships from your second or third year.", "Show real projects with a clear explanation of the problem, your choices and what improved."],
      ["QUALIFICATION / CERTIFICATIONS", "There is no compulsory licence. Once you know your direction, certifications from AWS, Google Cloud, Azure or specialised areas (data, security, mobile) can support your CV.", "Certifications add credibility; the portfolio and interview process still lead."],
      ["FIRST JOB / ENTRY POINT", "Common entry roles include graduate software engineer, junior developer, QA / SDET, and support engineer at product companies, services companies or startups.", "Your first team teaches you how real products are planned, reviewed, shipped and maintained."],
      ["SPECIALIZATION / GROWTH", "Grow into frontend, backend, mobile, data engineering, cloud, DevOps, security, ML engineering, product engineering or technical leadership.", "Follow the problems that make you lose track of time and keep learning new tools."],
    ],
    salary: [["STARTING OUT", "₹3L – ₹8L"], ["MID-CAREER", "₹9L – ₹22L"], ["EXPERIENCED", "₹22L+"]],
    salaryNote: "Ranges vary widely between service companies, product companies, top-tier tech firms and startups. Non-metro locations, freshers with fewer projects and less-known colleges usually see the lower end.",
    firstHandPerspective: "Software development is not only about writing new code. A big part of the job is reading existing code, understanding what someone else already built, debugging problems and testing changes carefully before they reach real users.",
  },

  "doctor": {
    slug: "doctor",
    name: "Doctor",
    color: "coral",
    tag: "Healthcare",
    description: "Use science and empathy to help people heal.",
    cardDescription: "Doctors combine science, careful decisions and human connection to diagnose illness and guide people towards better health.",
    intro: "Medicine asks you to stay curious, listen closely and keep learning. The work is challenging and often deeply meaningful, and the path is a long one.",
    tasks: [
      "Take detailed histories and examine patients",
      "Order and interpret tests such as blood work, imaging and pathology reports",
      "Diagnose conditions and recommend evidence-based treatment plans",
      "Prescribe medications and explain options in a clear, kind way",
      "Perform procedures within your area of training",
      "Coordinate care with nurses, specialists and other doctors",
      "Keep detailed clinical records and follow up on cases",
      "Keep learning as guidelines, evidence and technology evolve",
    ],
    dayCopy: "A doctor's day depends heavily on specialty and setting. This example is a hospital-based general medicine day; surgery, GP practice and ICU look very different.",
    timeline: [
      ["8:00", "Review overnight notes on assigned patients"],
      ["9:00", "Morning ward rounds"],
      ["11:00", "Outpatient consultations"],
      ["13:30", "Lunch and case discussions with the team"],
      ["14:30", "Procedures, follow-ups or investigations"],
      ["16:30", "Update case notes and treatment plans"],
      ["17:30", "Handover to the on-call team"],
    ],
    skills: [
      "Clinical assessment",
      "Diagnostic reasoning",
      "Test & imaging interpretation",
      "Procedural skills",
      "Prescribing",
      "Evidence-based medicine",
      "Empathy",
      "Decision-making under uncertainty",
      "Clear communication",
      "Resilience",
      "Listening",
      "Teamwork",
    ],
    roadmap: [
      ["STARTING POINT", "In Class 11-12, take PCB (Physics, Chemistry, Biology) and prepare for the NEET-UG entrance exam, which is the standard gateway to Indian medical colleges.", "Build steady study habits early; medicine is a marathon of learning."],
      ["EDUCATION / COURSE OPTIONS", "The main route in India is MBBS through NEET-UG (usually 5.5 years, including a 1-year compulsory rotating internship). Some students consider foreign medical universities recognised by the National Medical Commission (NMC), followed by the FMGE / NExT Step 1 as applicable.", "Understand fees, hostel costs, teaching quality and hospital exposure before choosing a college."],
      ["CLINICAL EXPERIENCE", "Complete supervised clinical rotations during MBBS and the compulsory rotating internship across medicine, surgery, paediatrics, obstetrics and other departments.", "Use rotations to notice which patients, problems and teams spark your curiosity."],
      ["QUALIFICATION / LICENSING", "After MBBS, register with your State Medical Council under the National Medical Commission framework to legally practise medicine in India.", "For specialist practice, plan early for the NEET-PG / NExT Step 2 route into MD, MS, DNB or diplomas."],
      ["FIRST JOB / ENTRY POINT", "Common entry roles include junior resident, medical officer, house officer or entry-level doctor at hospitals, primary health centres, clinics or public health programmes.", "Keep reflecting, ask for feedback and build trust with patients and colleagues."],
      ["SPECIALIZATION / GROWTH", "After PG, specialise in areas such as internal medicine, paediatrics, surgery, radiology, dermatology, psychiatry, public health or family medicine. Super-specialisations (DM / MCh) follow after MD / MS.", "There are many ways to make a difference in medicine — clinical practice, teaching, research, public health and policy all count."],
    ],
    salary: [["STARTING OUT", "₹5L – ₹10L"], ["MID-CAREER", "₹12L – ₹25L"], ["EXPERIENCED", "₹25L+"]],
    salaryNote: "Government roles follow pay commission scales and often include allowances. Specialists in metros and top private hospitals earn significantly more, and independent practice varies widely with location, reputation and years of work.",
    firstHandPerspective: "Medicine is a long-haul career. Studying continues long after MBBS, night duties and pressure are real, and the meaningful moments often come alongside challenging days. Understanding this upfront helps you choose the specialty and setting that fit you.",
  },

  "chartered-accountant": {
    slug: "chartered-accountant",
    name: "Chartered Accountant",
    color: "gold",
    tag: "Finance & Accounting",
    description: "Help people and businesses make confident decisions.",
    cardDescription: "Chartered accountants turn financial information into clear advice that helps businesses, teams and people move forward.",
    intro: "The work is not only about numbers. A CA reads the story behind financial data and helps people make responsible, informed decisions.",
    tasks: [
      "Prepare and review financial statements for clients or your organisation",
      "Conduct statutory, internal or tax audits",
      "File income tax and GST returns and handle scrutiny queries",
      "Advise clients on tax planning, compliance and business structures",
      "Investigate variances, spot risks and suggest process improvements",
      "Coordinate with regulators, auditors and management",
      "Explain complex financial rules to non-specialists in plain language",
      "Keep pace with changes in ICAI standards, tax law and reporting",
    ],
    timeline: [
      ["8:30", "Review priorities and deadlines"],
      ["9:00", "Work on client accounts, audit files or tax returns"],
      ["11:30", "Client or partner review meeting"],
      ["13:00", "Lunch"],
      ["14:00", "Draft reports, working papers and recommendations"],
      ["16:00", "Follow-up calls with clients or authorities"],
      ["17:00", "Send updates, plan the next day and log time"],
    ],
    skills: [
      "Financial accounting",
      "Auditing & assurance",
      "Direct tax (Income Tax)",
      "Indirect tax (GST)",
      "Ind AS / financial reporting standards",
      "Advanced MS Excel",
      "Tally / ERP systems",
      "Attention to detail",
      "Integrity",
      "Analytical thinking",
      "Clear writing",
      "Client communication",
    ],
    roadmap: [
      ["STARTING POINT", "After Class 10, register for the CA Foundation via ICAI once you complete Class 12. Commerce with Accounts helps, but students from Science and other streams also successfully take up the CA course.", "Build strong Excel, English and mental-maths habits early."],
      ["EDUCATION / COURSE OPTIONS", "The CA course by ICAI has three levels — Foundation, Intermediate and Final. Many students also pursue B.Com or BBA in parallel (often through distance education) to have an additional degree alongside their CA.", "Understand the current ICAI scheme carefully — exam patterns, subjects and articleship requirements are periodically updated."],
      ["PRACTICAL EXPERIENCE", "After clearing CA Intermediate (or one group of it), begin your 3-year articleship with a CA firm or eligible organisation. This is hands-on training in audit, tax, accounting and advisory work.", "Choose an articleship firm based on the mix of work you want, not only the brand name."],
      ["QUALIFICATION / PROFESSIONAL ROUTE", "Clear the CA Final examination, complete the required articleship period and ICAI training programmes to qualify as a Chartered Accountant and obtain ICAI membership.", "Plan your study leave and revision cycles realistically — CA Final is a serious commitment."],
      ["FIRST JOB / ENTRY POINT", "Common entry paths include audit associate, tax associate, financial analyst or industry roles across banks, corporates and consulting firms. Some CAs continue with their articleship firm; others move to Big 4 or industry.", "Your first role builds a practical point of view across clients, industries and deadlines."],
      ["SPECIALIZATION / GROWTH", "Grow into audit, tax, forensic accounting, transaction advisory, corporate finance, risk, controllership, CFO roles or start your own practice.", "CA skills travel across industries and into leadership or entrepreneurship."],
    ],
    salary: [["STARTING OUT", "₹6L – ₹10L"], ["MID-CAREER", "₹12L – ₹25L"], ["EXPERIENCED", "₹25L+"]],
    salaryNote: "Big 4 and top-tier firms, industry roles and specialised practices pay higher; independent practice depends heavily on client base, city and years of experience.",
    firstHandPerspective: "The CA journey is intense — three levels of exams, three years of articleship, long study hours and unpredictable deadlines. The upside is that once you qualify, the skills you build are recognised across industries and can travel with you into finance, consulting or your own practice.",
  },

  "entrepreneur": {
    slug: "entrepreneur",
    name: "Entrepreneur",
    color: "violet",
    tag: "Business & Management",
    description: "Spot opportunities and build something people need.",
    cardDescription: "Entrepreneurs turn observations into ideas, test what people need and bring teams together to build something useful.",
    intro: "Entrepreneurship is a path for curious people who enjoy making a first version, learning from it and trying again.",
    tasks: [
      "Talk to potential customers to learn which problems are worth solving",
      "Shape an idea into a small, testable first version of a product or service",
      "Register the business, open bank accounts and set up basic compliance",
      "Build a small team of co-founders, early hires or freelancers",
      "Sell early — reach out, run pilots and close first customers",
      "Track cash flow, revenue and runway, and decide where money goes",
      "Learn from what works and what doesn't, and adjust the plan",
      "Manage your own energy through a lot of uncertainty",
    ],
    dayCopy: "Founder days vary enormously by stage and industry. This is one example from an early-stage founder building a small software product.",
    timeline: [
      ["8:00", "Read industry news and plan the day"],
      ["9:00", "Customer conversations and demos"],
      ["11:00", "Product or content work with the team"],
      ["13:00", "Lunch with a co-founder or friend"],
      ["14:00", "Sales follow-ups and hiring calls"],
      ["16:00", "Metrics, cash flow and admin"],
      ["18:00", "Reflect, journal and plan tomorrow"],
    ],
    skills: [
      "Customer discovery",
      "Basic finance & unit economics",
      "Marketing & sales fundamentals",
      "Compliance & legal awareness",
      "Product thinking",
      "Hiring & team-building",
      "Storytelling",
      "Resourcefulness",
      "Adaptability",
      "Grit",
      "People skills",
    ],
    roadmap: [
      ["STARTING POINT", "Notice everyday problems, ask why things work the way they do, and build small communication, business and digital skills.", "A notebook of observations and small side projects is a surprisingly powerful place to start."],
      ["EDUCATION / COURSE OPTIONS", "There is no single required degree. Common routes in India include BBA, B.Com, B.Tech, design, arts or economics, plus incubators, startup programmes, MBA, and focused certifications on product, marketing or finance.", "Choose learning that helps you understand people, products, money and the specific industry you care about."],
      ["PRACTICAL EXPERIENCE", "Test an idea with real users, build a small first version, join a startup or work on a collaborative project.", "Feedback from real users is more useful than guessing alone."],
      ["QUALIFICATION / SETUP", "No professional licence is universal. Learn about business registration (proprietorship, LLP, private limited), GST, TDS and sector-specific permissions when they become relevant.", "Use a CA and a lawyer for decisions that affect customers, money or regulation."],
      ["FIRST JOB / ENTRY POINT", "Common early routes include founding your own venture, joining an early-stage startup, working in a founder's office, or product / business development / operations roles.", "A first role can teach you how ideas, customers and teams actually move together."],
      ["SPECIALIZATION / GROWTH", "Grow a venture, join an accelerator, lead product, become an operator-investor, mentor other founders or start again with what you learned.", "There is no single finish line for an entrepreneurial path."],
    ],
    salary: [["STARTING OUT", "Highly variable"], ["MID-CAREER", "₹6L – ₹20L"], ["EXPERIENCED", "₹20L+"]],
    salaryNote: "Founder income depends on the stage of your company, funding, personal choices and the industry. Many founders earn less than a corporate role in the early years and more in later years, with a wide range of outcomes.",
    firstHandPerspective: "Starting a company is not the movie version. Most of the work is unglamorous — talking to customers, writing the same email again, dealing with GST, chasing payments, hiring and firing. If those things feel meaningful to you, the job will suit you.",
  },

};